name: Media3 library Build

on:
   push:
     branches: [ "build" ]
   pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      FFMPEG_BRANCH: "release/6.0"
    
    steps:

    - name: Checkout Media3
      uses: actions/checkout@v4
      with:
          repository: androidx/media
          ref: release
          path: media

    - name: decoder_ffmpeg
      uses: actions/checkout@v4
      with:
          repository: FFmpeg/FFmpeg
          ref: release/6.0
          path: media/libraries/decoder_ffmpeg/src/main/jni/ffmpeg
          
    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: actions/setup-java@v1
      with:
         java-version: '17.x'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
         cmake-version: '3.16.x'
     
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
         ndk-version: r26c
         local-cache: true
   
    - run: ./build_ffmpeg.sh
          ${{ github.workspace }}media/libraries/decoder_ffmpeg/src/main
          ${{ steps.ndk.outputs.ndk-path }}
          $(uname -s | tr '[:upper:]' '[:lower:]')-x86_64
          21
          vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd
      working-directory: media/libraries/decoder_ffmpeg/src/main/jni

    - run: ./gradlew assembleRelease
   
    - name: Copy Artifacts
      run: |
          mkdir -p libs
          cp media/libraries/decoder_{ffmpeg}/buildout/outputs/aar/*.aar libs/
          cp media/libraries/{common,exoplayer,extractor,ui,session,datasource,decoder,container}/buildout/outputs/aar/*.aar libs/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: media3Lib
        path: libs/*
