name: Media3 library Build

on:
   push:
     branches: [ "build" ]
   pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PROJECT_USER: "l1068org"
      PROJECT_NAME: "media"
      MEDIA3_BRANCH: "r1.11.0-0.0.5"
      FFMPEG_BRANCH: "release/6.0"
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
          distribution: 'temurin'
          java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
     
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
          ndk-version: r29
          local-cache: false
          add-to-path: true

    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

    - uses: ilammy/setup-nasm@v1
    - name: Install Meson
      run: pip3 install --user meson

    - name: Build ffmpeg
      continue-on-error: false
      env:
          ANDROID_NDK_HOME: ${{steps.setup-ndk.outputs.ndk-path }}
          NDK_PATH: ${{ steps.setup-ndk.outputs.ndk-path }}
          ROOT_DIR: ${{ github.workspace }}
      run: |       
        echo "*** Setting up Media3 ***"
        git clone -b $MEDIA3_BRANCH https://github.com/$PROJECT_USER/$PROJECT_NAME.git
        
        # Set environment variables
        MEDIA3_ROOT="$PWD/$PROJECT_NAME"
        echo "*** Setting up FFMPEG ***"
        export FFMPEG_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_ffmpeg/src/main
        export HOST_PLATFORM="linux-x86_64"
        export ANDROID_ABI=21
        export ENABLED_DECODERS=(vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd)
        pushd $FFMPEG_MODULE_PATH/jni
        git clone -b $FFMPEG_BRANCH https://git.ffmpeg.org/ffmpeg.git
        rm -rf /usr/local/bin/cmake
        ./build_ffmpeg.sh "${FFMPEG_MODULE_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" "${ANDROID_ABI}" "${ENABLED_DECODERS[@]}"
        popd
        pushd $PROJECT_NAME
        
        echo "* Setting up AV1"
        AV1_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_av1/src/main
        cd "${AV1_MODULE_PATH}/jni" && git clone https://github.com/google/cpu_features -b v0.11.0
        cd "${AV1_MODULE_PATH}/jni" && git clone https://code.videolan.org/videolan/dav1d.git
        ./build_dav1d.sh "${AV1_MODULE_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}"
        popd
        pushd $PROJECT_NAME

        echo "* Setting up Flac decoder module"
        FLAC_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_flac/src/main          
        cd "${FLAC_MODULE_PATH}/jni" && git clone https://github.com/xiph/flac.git libflac
        popd
        pushd $PROJECT_NAME
        
        echo "* Setting up MPEGH decoder module"
        MPEGH_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_mpegh/src/main        
        cd "${MPEGH_MODULE_PATH}/jni" && git clone https://github.com/Fraunhofer-IIS/mpeghdec.git --branch r3.0.3 libmpegh
        popd
        pushd $PROJECT_NAME

        echo "* Setting up Opus decoder module"
        OPUS_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_opus/src/main          
        cd "${OPUS_MODULE_PATH}/jni" && git clone https://github.com/xiph/opus.git libopus
        popd
        pushd $PROJECT_NAME

        echo "* Setting up VP9 decoder module"
        VP9_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_vp9/src/main          
        cd "${VP9_MODULE_PATH}/jni" && git clone --depth=1 -b v1.15.2 https://chromium.googlesource.com/webm/libvpx libvpx
        chmod +x ./generate_libvpx_android_configs.sh
        ./generate_libvpx_android_configs.sh
        ${NDK_PATH}/ndk-build -j4
        popd
        pushd $PROJECT_NAME

        echo "* Setting up IAMF decoder AOMediaCodec module"
        IAMF_MODULE_PATH=$MEDIA3_ROOT/libraries/decoder_iamf/src/main          
        cd "${IAMF_MODULE_PATH}/jni" && git clone --depth=1 --revision=de364b983447a45d8be81f9172eea422c139dcf0 https://github.com/AOMediaCodec/iamf-tools.git iamf_tools
        ./build_iamf_tools.sh ${IAMF_MODULE_PATH}
        popd
        pushd $PROJECT_NAME
       

    - name: Build Media3 AARs
      run: |
          cd media
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          ./gradlew bundleReleaseAar
          
          #./gradlew :lib-decoder-{ffmpeg,av1,flac,iamf,mpegh,opus,vp9}:bundleReleaseAar
          #./gradlew :lib-{common,exoplayer,extractor,ui,session,datasource,decoder,container}:bundleReleaseAar
          #./gradlew :lib-{exoplayer-dash,exoplayer-hls,exoplayer-smoothstreaming,exoplayer-rtsp}:bundleReleaseAar

    - name: Collect AARs
      run: |
          mkdir -p libs
          cp media/libraries/*/buildout/outputs/aar/*-release.aar libs/
          #cp $MEDIA3_ROOT/libraries/decoder_{ffmpeg,av1,flac,iamf,mpegh,opus,vp9}/buildout/outputs/aar/*.aar libs/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: media3Lib
        path: libs/*
        
    - name: Clone target repository
      env:
         GIT_TOKEN: ${{ secrets.REPO_TOKEN }}
         REPO_USER: ${{ secrets.REPO_NAME }}
      run: |
        git clone https://${GIT_TOKEN}@github.com/${REPO_USER}/media.git  media3Libs
        cd media3Libs
        git checkout -b CI || git checkout CI

    - name: Copy libs folder to target repository
      run: |
        mkdir -p media3Libs/libs
        cp -r libs/* media3Libs/libs
        cd media3Libs
        git add .
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update libs folder with latest build artifacts"

        echo 'jdk:
           - openjdk17
        install:
           - |
             cd libs
             for lib in *; do
             libName=${lib//.aar/}
      
             mvn install:install-file \
               -Dfile=$lib \
               -DgroupId=com.l1068.media \
               -DartifactId=$libName \
               -Dversion=$VERSION \
               -Dpackaging=aar \
               -DgeneratePom=true
              done' > jitpack.yml
         git add jitpack.yml
         git commit -m "Update jitpack.yml"
         git push origin CI --force
    - name: Push changes to CI branch
      run: |
        cd media3Libs
        git push -f origin CI
        
